// <auto-generated />
namespace BookShop.Data.Sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NonNullableCover : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NonNullableCover));
        
        string IMigrationMetadata.Id
        {
            get { return "201701171128156_NonNullableCover"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
